import { Link, Outlet, useLocation, useNavigate } from "react-router-dom";
import { BarChart3, BriefcaseBusiness, Building2, CreditCard, FileCheck2, LayoutDashboard, LogOut, Settings, Users, WalletCards, Menu, X } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import Logo from "../components/common/Logo";

const items = [
 ["/admin","Dashboard",LayoutDashboard], ["/admin/jobs","Jobs",BriefcaseBusiness], ["/admin/companies","Companies",Building2], ["/admin/plans","Subscription Plans",CreditCard], ["/admin/users","Users",Users], ["/admin/applications","Applications",FileCheck2], ["/admin/payments","Payments",WalletCards], ["/admin/revenue","Revenue",BarChart3], ["/admin/settings","Settings",Settings]
];
export default function AdminLayout(){const location=useLocation();const navigate=useNavigate();const {user,logout}=useAuth();const [open,setOpen]=useState(false);const nav=()=>{logout();navigate('/login')};const Sidebar=()=> <div className="flex h-full flex-col"><div className="border-b border-[#edf1f7] p-6"><Logo/></div><div className="flex-1 p-4"><div className="mb-3 px-3 text-[10px] font-extrabold uppercase tracking-widest text-[#9aa6bb]">Administration</div>{items.map(([to,label,Icon])=><Link key={to} onClick={()=>setOpen(false)} to={to} className={`mb-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${(location.pathname===to || (to!=="/admin" && location.pathname.startsWith(to+"/")))?"bg-[#eef1ff] text-[#3157f5]":"text-[#60708d] hover:bg-[#f5f7fb]"}`}><Icon size={17}/>{label}</Link>)}</div><div className="border-t border-[#edf1f7] p-4"><div className="mb-3 px-3 text-xs text-[#7c8aa5] truncate">{user?.email}</div><button onClick={nav} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-red-500 hover:bg-red-50"><LogOut size={17}/> Logout</button></div></div>;
return <div className="min-h-screen bg-[#f5f8fd]"><aside className="fixed inset-y-0 left-0 hidden w-[250px] border-r border-[#e5ebf5] bg-white lg:block"><Sidebar/></aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-black/30" onClick={()=>setOpen(false)}/><aside className="relative h-full w-[280px] bg-white shadow-xl"><div className="absolute right-3 top-3"><button onClick={()=>setOpen(false)} className="rounded-lg p-2"><X size={20}/></button></div><Sidebar/></aside></div>}<div className="lg:ml-[250px]"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-[#e5ebf5] bg-white/95 px-4 backdrop-blur sm:px-6"><button className="rounded-lg p-2 lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="ml-2"><div className="text-lg font-extrabold text-[#102044]">JobOrbit Admin</div><div className="hidden text-xs text-[#8996ad] sm:block">Owner management panel</div></div><div className="flex items-center gap-3"><Link to="/" className="btn-secondary !py-2 text-xs">View Website</Link></div></header><main className="p-4 sm:p-7"><Outlet/></main></div></div>}
