import { Link } from "react-router-dom";
import { useEffect,useState } from "react";
import { Edit3, Eye, Plus, Trash2 } from "lucide-react";
import { getAdminJobs, deleteJob, updateJob } from "../../services/jobService";
export default function ManageJobs(){
 const [jobs,setJobs]=useState([]); const [q,setQ]=useState(""); const [status,setStatus]=useState("all");
 const load=()=>getAdminJobs({search:q,published:status==='all'?undefined:status==='published'}).then(r=>setJobs(r.data.jobs||[])).catch(()=>{});
 useEffect(()=>{load()},[]);
 const remove=async id=>{if(!confirm('Delete this job?'))return;await deleteJob(id);load()};
 const toggle=async j=>{await updateJob(j._id,{published:!j.published});load()};
 return <div><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-sm font-bold text-[#3157f5]">Content management</div><h1 className="text-2xl font-extrabold text-[#102044]">Job Openings</h1><p className="mt-1 text-sm text-[#7c8aa5]">Fetch company jobs, review them and publish them on JobOrbit.</p></div><Link to="/admin/jobs/add" className="btn-primary"><Plus size={17}/> Add Job</Link></div><div className="soft-card mt-5 flex flex-col gap-3 p-4 md:flex-row"><input className="input" placeholder="Search title or location" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><select className="input md:max-w-[180px]" value={status} onChange={e=>{setStatus(e.target.value);setTimeout(load,0)}}><option value="all">All statuses</option><option value="published">Published</option><option value="false">Drafts</option></select><button className="btn-primary" onClick={load}>Search</button></div><div className="soft-card mt-5 overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b bg-[#fafbfe] text-xs uppercase text-[#8a97ad]"><tr><th className="p-4">Job</th><th>Company</th><th>Location</th><th>Source</th><th>Status</th><th>Actions</th></tr></thead><tbody>{jobs.map(j=><tr key={j._id} className="border-b last:border-0"><td className="p-4"><div className="font-bold text-[#102044]">{j.title}</div><div className="mt-1 text-xs text-[#7c8aa5]">{j.jobType||'Full Time'}</div></td><td>{j.company?.name||'—'}</td><td>{j.location||'—'}</td><td><a className="max-w-[190px] truncate block text-[#3157f5]" href={j.sourceUrl} target="_blank" rel="noreferrer">Original job ↗</a></td><td><button onClick={()=>toggle(j)} className={`rounded-full px-2.5 py-1 text-xs font-bold ${j.published?'bg-[#e9f8ef] text-[#1a8d5b]':'bg-[#fff4e6] text-[#b86b00]'}`}>{j.published?'Published':'Draft'}</button></td><td><div className="flex gap-3"><Link title="View" to={`/jobs/${j._id}`} className="text-[#3157f5]"><Eye size={17}/></Link><Link title="Edit" to={`/admin/jobs/${j._id}/edit`} className="text-[#3157f5]"><Edit3 size={17}/></Link><button title="Delete" onClick={()=>remove(j._id)} className="text-red-500"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table>{!jobs.length&&<div className="p-10 text-center text-sm text-[#7c8aa5]">No jobs found.</div>}</div></div>
}
